### ISSUE TITLE
What about browserstack?

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website-qa#53]
@boly38, do you know browserstack? They offer free license for opensource projects https://www.browserstack.com/open-source

That may help to check cross browser compatibility, no?

**Comment by boly38** [comment]
I'm not QA expert, so no I dont know, but when I will start moving qa for new-them, I will study this one sur, thanks for the input.

**Comment by boly38** [comment]
- we have a browserstack team :

I added team-private details on [this post](https://groups.google.com/forum/#!topic/geokrety-contrib/w9id5nMIE7E)

- I just add `BS_USERNAME` and `BS_TOKEN`(hidden) to [travis-ci > website-qa > settings > variables](https://travis-ci.org/geokrety/geokrety-website-qa/settings).

**Comment by kumy** [comment]
>     * we have a browserstack team :
Yeah!

>     * I just add `BS_USERNAME` and `BS_TOKEN`(hidden) to [travis-ci > website-qa > settings > variables](https://travis-ci.org/geokrety/geokrety-website-qa/settings).
I've joined the GeoKrety account as a user to the party, @boly38 may I change the stored credentials in Travis by the one from the GeoKrety bot?

**Comment by boly38** [comment]
of course I let you do that. 
I set you 'admin' there's only one 'owner' role I could transfer it to geokrety user if needed.

**Comment by kumy** [comment]
> I could transfer it to geokrety user if needed.
Doesn't matter right now, but it would be nice if all our external tools like BS, Codacy are aligned to this permission scheme

**Comment by boly38** [comment]
Open plan:

> What you get for free: Unlimited manual and automated testing for open source websites and mobile apps. Full platform access to Live, Automate, App Live and App Automate. Total of 5 user licenses and parallels.
>  
> What we request in return: Give us a shoutout on your GitHub project page or website. Post and hyperlink our attached logo, and a line about how you use BrowserStack. We are counting on you to help us spread the word to the open source community.

**Comment by boly38** [comment]
badge try with brice account: 
[![BrowserStack Status](https://automate.browserstack.com/badge.svg?badge_key=SGZSTjVSc2d0d1FSRDg4c1c3bE80akFPVVk3anBySFQ0REk5SVBkbWxaOD0tLXIrL3FRMjFVcFZtZzJEV1VITVJ1ZVE9PQ%3D%3D--3680a826bcdde55a8dec3a3d1a086bcac9a48fd8)](https://automate.browserstack.com/public-build/SGZSTjVSc2d0d1FSRDg4c1c3bE80akFPVVk3anBySFQ0REk5SVBkbWxaOD0tLXIrL3FRMjFVcFZtZzJEV1VITVJ1ZVE9PQ%3D%3D--3680a826bcdde55a8dec3a3d1a086bcac9a48fd8)

**Comment by boly38** [comment]
on demand only: we could so ask browser stack to run if and only if a tag containing `bs-` is detected

[example](https://stackoverflow.com/questions/50831785/travis-manually-confirm-next-stage)
 
    if: tag =~ bs-

kind of [conditional stage](https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#conditional-stages) using regex
